version: "3.1"
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=k;Mb(#XQoQ!_Ez0M
      - POSTGRES_DB=rss

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=LfvU9~Ps%ef+f4r
    command: server /data --console-address ":9001"
