version: "3.1"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=helloworld
      - POSTGRES_DB=rss
    ports:
      - 5432:5432
  backend:
    image: rsshub-backend:v1.0.0
    restart: always
    ports:
      - 10000:10000